# Generated by Django 4.2.3 on 2024-05-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaDeCoser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('rpm', models.FloatField()),
                ('puntadas_por_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('rol', models.IntegerField(choices=[(1, 'administrador'), (2, 'usuario')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('idFicha', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('operacion', models.CharField(max_length=150)),
                ('codigo_Operacion', models.CharField(max_length=150)),
                ('ref', models.CharField(max_length=150)),
                ('modulo', models.CharField(max_length=150)),
                ('ppp', models.CharField(max_length=150)),
                ('minTurno', models.IntegerField()),
                ('suplementos', models.CharField(max_length=150)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
                ('tipoMaquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.maquinadecoser')),
            ],
        ),
    ]
