# Generated by Django 4.2.3 on 2024-05-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='rpm',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maquinadecoser',
            name='rpm',
            field=models.ImageField(upload_to=''),
        ),
    ]
