# Generated by Django 4.2.3 on 2024-05-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_operacion_alter_fichatecnica_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='operacion',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='operacion',
        ),
    ]
