# Generated by Django 4.2.3 on 2024-05-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_operacion_alter_fichatecnica_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplemento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Turno', models.IntegerField(null=True)),
            ],
        ),
    ]
