# Generated by Django 4.2.3 on 2024-05-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_suplemento_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='Turno',
            new_name='turno',
        ),
    ]
