# Generated by Django 4.2.3 on 2024-05-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_turno_turno_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='minTurno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='suplementos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suplemento'),
        ),
    ]
