# Generated by Django 5.0.6 on 2024-05-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_fichatecnica_minturno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gtf',
            fields=[
                ('idGtf', models.BigAutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=150)),
                ('valor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Presicion_de_parada',
            fields=[
                ('idGtf', models.BigAutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=150)),
                ('valor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='constante',
            field=models.FloatField(default=0.0006),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='distanciaCostura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='factorAltaVelocidad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='numeroParadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='paradaArranque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='tiempoMinimoCostura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='tipoTela',
            field=models.CharField(default=1.0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='tmuCostura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='gtf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.gtf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='presicionParada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.presicion_de_parada'),
            preserve_default=False,
        ),
    ]
