# Generated by Django 5.0.6 on 2024-05-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_gtf_presicion_de_parada_fichatecnica_constante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presicion_de_parada',
            old_name='idGtf',
            new_name='idParada',
        ),
    ]
