# Generated by Django 5.0.6 on 2024-05-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_idgtf_presicion_de_parada_idparada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos_GSD',
            fields=[
                ('Numero', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('movimiento', models.CharField(max_length=150)),
                ('tmu', models.IntegerField()),
                ('dn', models.IntegerField(blank=True, null=True)),
                ('secuencia', models.CharField(blank=True, max_length=150, null=True)),
                ('v1', models.FloatField(blank=True, null=True)),
                ('v2', models.FloatField(blank=True, null=True)),
                ('v3', models.FloatField(blank=True, null=True)),
                ('v4', models.FloatField(blank=True, null=True)),
                ('v5', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioDinamico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Numero', models.IntegerField()),
                ('codigo', models.CharField(max_length=150)),
                ('movimiento', models.CharField(max_length=150)),
                ('frecuencia', models.IntegerField()),
                ('distancia', models.IntegerField()),
                ('tmu', models.ImageField(upload_to='')),
                ('totalTmu', models.FloatField()),
                ('tiempoSam', models.FloatField()),
                ('fichaTecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fichatecnica')),
            ],
        ),
    ]
